[package]
name = "ck_cli"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
anyhow = "1"
clap = { version = "4", features = ["derive"] }
dirs = "6"

ck_git = { path = "../ck_git" }
ck_context = { path = "../ck_context" }
ck_storage = { path = "../ck_storage" }
ck_workspace = { path = "../ck_workspace" }
ck_models = { path = "../ck_models" }
ck_diff = { path = "../ck_diff" }